package config

import (
	"errors"
)

var (
	EmailAddressIsEmpty = errors.New("メールアドレスが入力されていません")
	UserNameIsEmpty = errors.New("ユーザー名が入力されていません")
	PasswordIsEmpty = errors.New("パスワードが入力されていません")
	UserAlreadyExists = errors.New("ユーザーがすでに登録されています")
	LoginFailed = errors.New("ログインに失敗しました")
	AvailableTimeNotFound = errors.New("ミーティング可能な時間が見つかりません")
	AvailableTimeTooLong = errors.New("入力されたミーティング時間が長すぎます")
	AvailableTimeOutOfLimit = errors.New("入力された時間帯はミーティング可能な時間帯の範囲外です")
	TitleIsEmpty = errors.New("タイトルが入力されていません")
	HourIsEmpty = errors.New("時間が入力されていません")
	MeetingNotFound = errors.New("ミーティングが見つかりませんでした")
	PlaceIsNotSpecified = errors.New("開催場所が指定されていません")
	URLIsNotSpecified = errors.New("URLが指定されていません")
	NeitherPlaceOrURLIsSpecified = errors.New("開催場所もURLも指定されていません")
	CandidateTimeIsEmpty = errors.New("ミーティング候補時間が入力されていません")
	CandidateTimeIsPast = errors.New("過去のミーティング候補時間があります")
	ErrIdConversionFailed = errors.New("IDのint型への変換に失敗しました")
	ErrFailedToBindUser = errors.New("User型への変換に失敗しました")
	ErrUserIsNil = errors.New("Userのポインタがnullです")
	ErrListOfErrorsNotFound = errors.New("エラーメッセージの配列が見つかりませんでした")
	ErrEmailAddressIsEmpty = errors.New("メールアドレスが入力されていません")
	ErrEmailAddressNotFound = errors.New("メールアドレスが見つかりませんでした")
	ErrUserNotFound = errors.New("ユーザーが見つかりませんでした")
	ErrUserNameNotFound = errors.New("ユーザー名が見つかりませんでした")
	ErrUserWithUserNameNotFound = errors.New("入力されたユーザー名を持つユーザーが見つかりませんでした")
	ErrUserWithUserIdNotFound = errors.New("入力されたユーザーIDを持つユーザーが見つかりませんでした")
	ErrUserIdWithEmailAddressNotFound = errors.New("入力されたメールアドレスを持つユーザーのIDが見つかりませんでしたでした")
	ErrFailedToResetPassword = errors.New("パスワードの変更に失敗しました")
	ErrMeetingNotFound = errors.New("ミーティングが存在しませんが見つかりませんでした")
	ErrMeetingHourIsNegative = errors.New("ミーティング時間は0より大きい値を入力して下さい")
	ErrRecordNotFound = errors.New("DBのレコードが見つかりませんでした")
	ErrArrayIsNil = errors.New("配列のポインタがnullでした")
	ErrArrayIsEmpty = errors.New("配列が空でした")
	ErrCandidateTimeNotFound = errors.New("ミーティング候補時間が見つかりませんでした")
	ErrAvailableTimeIsNil = errors.New("ミーティング可能時間のポインタがnullです")
	ErrParticipantIsNil = errors.New("参加者のポインタがnullです")
	ErrParticipantWithUserNameIsNil = errors.New("ユーザー名付き参加者のポインタがnullです")
	ErrParticipantListIsEmpty = errors.New("参加者の配列が空です")
	ErrParticipantListIsNil = errors.New("参加者の配列のポインタがnullです")
	ErrParticipantWithUserNameListIsEmpty = errors.New("ユーザー名付き参加者が空です")
	ErrParticipantWithUserNameListIsNil = errors.New("ユーザー名付き参加者の配列のポインタがnullです")
	ErrParticipantWithUserNameListFailedToRegister = errors.New("ユーザー名付き参加者の配列の登録に失敗しました")
	ErrIntegerIsNil = errors.New("Int型のポインタがnullです")
)
